In [1]:
import pandas as pd

In [2]:
# Load the dataset
df = pd.read_csv('datasets/komoditas_beras_2022_2026.csv')

# Display the first few rows to verify
print("Initial Data:")
display(df.head())

Initial Data:

,Date_Scraped,Date_Param,Commodity_ID,Commodity_Name,Province_ID,Province_Name,Price,Price_Type
0,2026-02-12,2022-01-01,1,Beras,1,Aceh,10250.0,1
1,2026-02-12,2022-01-01,1,Beras,2,Sumatera Utara,11150.0,1
2,2026-02-12,2022-01-01,1,Beras,3,Sumatera Barat,13250.0,1
3,2026-02-12,2022-01-01,1,Beras,4,Riau,12250.0,1
4,2026-02-12,2022-01-01,1,Beras,5,Kepulauan Riau,13550.0,1

In [3]:
# Filter by Province_ID
target_province_id = 15

filtered_df = df[df['Province_ID'] == target_province_id]

# Display the filtered data
print(f"\nData for Province ID {target_province_id}:")
display(filtered_df)

Data for Province ID 15:

,Date_Scraped,Date_Param,Commodity_ID,Commodity_Name,Province_ID,Province_Name,Price,Price_Type
14,2026-02-12,2022-01-01,1,Beras,15,DI Yogyakarta,11250.0,1
48,2026-02-12,2022-01-02,1,Beras,15,DI Yogyakarta,11250.0,1
82,2026-02-12,2022-01-03,1,Beras,15,DI Yogyakarta,11250.0,1
116,2026-02-12,2022-01-04,1,Beras,15,DI Yogyakarta,11250.0,1
150,2026-02-12,2022-01-05,1,Beras,15,DI Yogyakarta,11250.0,1
...,...,...,...,...,...,...,...,...
47055,2026-02-13,2026-02-08,1,Beras,15,DI Yogyakarta,14200.0,1
47089,2026-02-13,2026-02-09,1,Beras,15,DI Yogyakarta,14200.0,1
47123,2026-02-13,2026-02-10,1,Beras,15,DI Yogyakarta,14200.0,1
47157,2026-02-13,2026-02-11,1,Beras,15,DI Yogyakarta,14200.0,1
47191,2026-02-13,2026-02-12,1,Beras,15,DI Yogyakarta,14200.0,1

In [4]:
# Export the filtered data to a CSV file
output_filename = f'filtered_data_province_yogyakarta.csv'
filtered_df.to_csv(output_filename, index=False)
print(f"Data exported to {output_filename}")

Data exported to filtered_data_province_yogyakarta.csv